/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MisAlertasRouteImport } from './routes/mis-alertas'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicamentoSlugRouteImport } from './routes/medicamento.$slug'
import { Route as AdminPreciosRouteImport } from './routes/admin.precios'
import { Route as ApiPublicHooksSeedCimaRouteImport } from './routes/api/public/hooks/seed-cima'
import { Route as ApiPublicHooksScrapePricesRouteImport } from './routes/api/public/hooks/scrape-prices'
import { Route as ApiPublicHooksNightlyGrowRouteImport } from './routes/api/public/hooks/nightly-grow'
import { Route as ApiPublicHooksEnrichMedsRouteImport } from './routes/api/public/hooks/enrich-meds'
import { Route as ApiPublicHooksDiscoverOnDemandRouteImport } from './routes/api/public/hooks/discover-on-demand'
import { Route as ApiPublicHooksDiscoverMedsRouteImport } from './routes/api/public/hooks/discover-meds'

const MisAlertasRoute = MisAlertasRouteImport.update({
  id: '/mis-alertas',
  path: '/mis-alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentoSlugRoute = MedicamentoSlugRouteImport.update({
  id: '/medicamento/$slug',
  path: '/medicamento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreciosRoute = AdminPreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksSeedCimaRoute = ApiPublicHooksSeedCimaRouteImport.update({
  id: '/api/public/hooks/seed-cima',
  path: '/api/public/hooks/seed-cima',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapePricesRoute =
  ApiPublicHooksScrapePricesRouteImport.update({
    id: '/api/public/hooks/scrape-prices',
    path: '/api/public/hooks/scrape-prices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNightlyGrowRoute =
  ApiPublicHooksNightlyGrowRouteImport.update({
    id: '/api/public/hooks/nightly-grow',
    path: '/api/public/hooks/nightly-grow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEnrichMedsRoute =
  ApiPublicHooksEnrichMedsRouteImport.update({
    id: '/api/public/hooks/enrich-meds',
    path: '/api/public/hooks/enrich-meds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDiscoverOnDemandRoute =
  ApiPublicHooksDiscoverOnDemandRouteImport.update({
    id: '/api/public/hooks/discover-on-demand',
    path: '/api/public/hooks/discover-on-demand',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDiscoverMedsRoute =
  ApiPublicHooksDiscoverMedsRouteImport.update({
    id: '/api/public/hooks/discover-meds',
    path: '/api/public/hooks/discover-meds',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
  '/api/public/hooks/discover-meds': typeof ApiPublicHooksDiscoverMedsRoute
  '/api/public/hooks/discover-on-demand': typeof ApiPublicHooksDiscoverOnDemandRoute
  '/api/public/hooks/enrich-meds': typeof ApiPublicHooksEnrichMedsRoute
  '/api/public/hooks/nightly-grow': typeof ApiPublicHooksNightlyGrowRoute
  '/api/public/hooks/scrape-prices': typeof ApiPublicHooksScrapePricesRoute
  '/api/public/hooks/seed-cima': typeof ApiPublicHooksSeedCimaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
  '/api/public/hooks/discover-meds': typeof ApiPublicHooksDiscoverMedsRoute
  '/api/public/hooks/discover-on-demand': typeof ApiPublicHooksDiscoverOnDemandRoute
  '/api/public/hooks/enrich-meds': typeof ApiPublicHooksEnrichMedsRoute
  '/api/public/hooks/nightly-grow': typeof ApiPublicHooksNightlyGrowRoute
  '/api/public/hooks/scrape-prices': typeof ApiPublicHooksScrapePricesRoute
  '/api/public/hooks/seed-cima': typeof ApiPublicHooksSeedCimaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
  '/api/public/hooks/discover-meds': typeof ApiPublicHooksDiscoverMedsRoute
  '/api/public/hooks/discover-on-demand': typeof ApiPublicHooksDiscoverOnDemandRoute
  '/api/public/hooks/enrich-meds': typeof ApiPublicHooksEnrichMedsRoute
  '/api/public/hooks/nightly-grow': typeof ApiPublicHooksNightlyGrowRoute
  '/api/public/hooks/scrape-prices': typeof ApiPublicHooksScrapePricesRoute
  '/api/public/hooks/seed-cima': typeof ApiPublicHooksSeedCimaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/mis-alertas'
    | '/admin/precios'
    | '/medicamento/$slug'
    | '/api/public/hooks/discover-meds'
    | '/api/public/hooks/discover-on-demand'
    | '/api/public/hooks/enrich-meds'
    | '/api/public/hooks/nightly-grow'
    | '/api/public/hooks/scrape-prices'
    | '/api/public/hooks/seed-cima'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/mis-alertas'
    | '/admin/precios'
    | '/medicamento/$slug'
    | '/api/public/hooks/discover-meds'
    | '/api/public/hooks/discover-on-demand'
    | '/api/public/hooks/enrich-meds'
    | '/api/public/hooks/nightly-grow'
    | '/api/public/hooks/scrape-prices'
    | '/api/public/hooks/seed-cima'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/mis-alertas'
    | '/admin/precios'
    | '/medicamento/$slug'
    | '/api/public/hooks/discover-meds'
    | '/api/public/hooks/discover-on-demand'
    | '/api/public/hooks/enrich-meds'
    | '/api/public/hooks/nightly-grow'
    | '/api/public/hooks/scrape-prices'
    | '/api/public/hooks/seed-cima'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  MisAlertasRoute: typeof MisAlertasRoute
  MedicamentoSlugRoute: typeof MedicamentoSlugRoute
  ApiPublicHooksDiscoverMedsRoute: typeof ApiPublicHooksDiscoverMedsRoute
  ApiPublicHooksDiscoverOnDemandRoute: typeof ApiPublicHooksDiscoverOnDemandRoute
  ApiPublicHooksEnrichMedsRoute: typeof ApiPublicHooksEnrichMedsRoute
  ApiPublicHooksNightlyGrowRoute: typeof ApiPublicHooksNightlyGrowRoute
  ApiPublicHooksScrapePricesRoute: typeof ApiPublicHooksScrapePricesRoute
  ApiPublicHooksSeedCimaRoute: typeof ApiPublicHooksSeedCimaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mis-alertas': {
      id: '/mis-alertas'
      path: '/mis-alertas'
      fullPath: '/mis-alertas'
      preLoaderRoute: typeof MisAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicamento/$slug': {
      id: '/medicamento/$slug'
      path: '/medicamento/$slug'
      fullPath: '/medicamento/$slug'
      preLoaderRoute: typeof MedicamentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/precios': {
      id: '/admin/precios'
      path: '/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AdminPreciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/seed-cima': {
      id: '/api/public/hooks/seed-cima'
      path: '/api/public/hooks/seed-cima'
      fullPath: '/api/public/hooks/seed-cima'
      preLoaderRoute: typeof ApiPublicHooksSeedCimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-prices': {
      id: '/api/public/hooks/scrape-prices'
      path: '/api/public/hooks/scrape-prices'
      fullPath: '/api/public/hooks/scrape-prices'
      preLoaderRoute: typeof ApiPublicHooksScrapePricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nightly-grow': {
      id: '/api/public/hooks/nightly-grow'
      path: '/api/public/hooks/nightly-grow'
      fullPath: '/api/public/hooks/nightly-grow'
      preLoaderRoute: typeof ApiPublicHooksNightlyGrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enrich-meds': {
      id: '/api/public/hooks/enrich-meds'
      path: '/api/public/hooks/enrich-meds'
      fullPath: '/api/public/hooks/enrich-meds'
      preLoaderRoute: typeof ApiPublicHooksEnrichMedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover-on-demand': {
      id: '/api/public/hooks/discover-on-demand'
      path: '/api/public/hooks/discover-on-demand'
      fullPath: '/api/public/hooks/discover-on-demand'
      preLoaderRoute: typeof ApiPublicHooksDiscoverOnDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover-meds': {
      id: '/api/public/hooks/discover-meds'
      path: '/api/public/hooks/discover-meds'
      fullPath: '/api/public/hooks/discover-meds'
      preLoaderRoute: typeof ApiPublicHooksDiscoverMedsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPreciosRoute: typeof AdminPreciosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPreciosRoute: AdminPreciosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  MisAlertasRoute: MisAlertasRoute,
  MedicamentoSlugRoute: MedicamentoSlugRoute,
  ApiPublicHooksDiscoverMedsRoute: ApiPublicHooksDiscoverMedsRoute,
  ApiPublicHooksDiscoverOnDemandRoute: ApiPublicHooksDiscoverOnDemandRoute,
  ApiPublicHooksEnrichMedsRoute: ApiPublicHooksEnrichMedsRoute,
  ApiPublicHooksNightlyGrowRoute: ApiPublicHooksNightlyGrowRoute,
  ApiPublicHooksScrapePricesRoute: ApiPublicHooksScrapePricesRoute,
  ApiPublicHooksSeedCimaRoute: ApiPublicHooksSeedCimaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
