/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MisAlertasRouteImport } from './routes/mis-alertas'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicamentoSlugRouteImport } from './routes/medicamento.$slug'

const MisAlertasRoute = MisAlertasRouteImport.update({
  id: '/mis-alertas',
  path: '/mis-alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentoSlugRoute = MedicamentoSlugRouteImport.update({
  id: '/medicamento/$slug',
  path: '/medicamento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/buscar' | '/mis-alertas' | '/medicamento/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/buscar' | '/mis-alertas' | '/medicamento/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/mis-alertas'
    | '/medicamento/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  MisAlertasRoute: typeof MisAlertasRoute
  MedicamentoSlugRoute: typeof MedicamentoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mis-alertas': {
      id: '/mis-alertas'
      path: '/mis-alertas'
      fullPath: '/mis-alertas'
      preLoaderRoute: typeof MisAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicamento/$slug': {
      id: '/medicamento/$slug'
      path: '/medicamento/$slug'
      fullPath: '/medicamento/$slug'
      preLoaderRoute: typeof MedicamentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  MisAlertasRoute: MisAlertasRoute,
  MedicamentoSlugRoute: MedicamentoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
