/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MisAlertasRouteImport } from './routes/mis-alertas'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicamentoSlugRouteImport } from './routes/medicamento.$slug'

const MisAlertasRoute = MisAlertasRouteImport.update({
  id: '/mis-alertas',
  path: '/mis-alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentoSlugRoute = MedicamentoSlugRouteImport.update({
  id: '/medicamento/$slug',
  path: '/medicamento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mis-alertas': typeof MisAlertasRoute
  '/medicamento/$slug': typeof MedicamentoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/mis-alertas'
    | '/medicamento/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/mis-alertas'
    | '/medicamento/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/mis-alertas'
    | '/medicamento/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  MisAlertasRoute: typeof MisAlertasRoute
  MedicamentoSlugRoute: typeof MedicamentoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mis-alertas': {
      id: '/mis-alertas'
      path: '/mis-alertas'
      fullPath: '/mis-alertas'
      preLoaderRoute: typeof MisAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicamento/$slug': {
      id: '/medicamento/$slug'
      path: '/medicamento/$slug'
      fullPath: '/medicamento/$slug'
      preLoaderRoute: typeof MedicamentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  MisAlertasRoute: MisAlertasRoute,
  MedicamentoSlugRoute: MedicamentoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
