
INSERT INTO public.medications (slug, name, active_ingredient, presentation, category, indication, brand_names) VALUES
('tantum-verde-spray', 'Tantum Verde Spray', 'Benzidamina', 'Spray bucal 30 ml', 'Antiinflamatorio', 'Dolor de garganta', ARRAY['Tantum','Tantum Verde','Benzirin']),
('tantum-verde-gargaras', 'Tantum Verde Gárgaras', 'Benzidamina', 'Solución 120 ml', 'Antiinflamatorio', 'Dolor de garganta', ARRAY['Tantum','Tantum Verde']),
('buscapina-10', 'Buscapina 10 mg', 'Butilbromuro de hioscina', 'Caja x 20 grageas', 'Antiespasmódico', 'Cólicos abdominales', ARRAY['Buscapina','Buscopan']),
('alka-seltzer', 'Alka-Seltzer', 'Ácido acetilsalicílico + bicarbonato', 'Caja x 12 tabletas efervescentes', 'Antiácido', 'Acidez y dolor', ARRAY['Alka-Seltzer','Alka Seltzer']),
('mejoral', 'Mejoral', 'Acetaminofén + cafeína', 'Caja x 24 tabletas', 'Analgésico', 'Dolor de cabeza', ARRAY['Mejoral','Mejoralito']),
('vick-vaporub', 'Vick VapoRub', 'Mentol + alcanfor + eucalipto', 'Frasco 50 g', 'Descongestionante', 'Resfriado y tos', ARRAY['Vick VapoRub','VapoRub','Vick']),
('vick-44', 'Vick 44', 'Dextrometorfano', 'Jarabe 120 ml', 'Antitusivo', 'Tos seca', ARRAY['Vick 44','Vick']),
('atamel-forte', 'Atamel Forte 650 mg', 'Acetaminofén', 'Caja x 30 tabletas', 'Analgésico', 'Dolor y fiebre', ARRAY['Atamel','Atamel Forte','Acetaminofén']),
('voltaren-emulgel', 'Voltaren Emulgel', 'Diclofenac', 'Tubo 60 g', 'Antiinflamatorio', 'Dolor muscular', ARRAY['Voltaren','Voltaren Emulgel','Cataflam Gel']),
('cataflam-50', 'Cataflam 50 mg', 'Diclofenac potásico', 'Caja x 20 grageas', 'Antiinflamatorio', 'Dolor e inflamación', ARRAY['Cataflam','Voltaren']),
('mucosolvan', 'Mucosolvan', 'Ambroxol', 'Jarabe 120 ml', 'Mucolítico', 'Tos con flema', ARRAY['Mucosolvan','Ambroxol','Mucoangin']),
('bisolvon', 'Bisolvon', 'Bromhexina', 'Jarabe 120 ml', 'Mucolítico', 'Tos con flema', ARRAY['Bisolvon','Bromhexina']),
('strepsils', 'Strepsils', 'Amilmetacresol + diclorobencilico', 'Caja x 24 pastillas', 'Antiséptico bucal', 'Dolor de garganta', ARRAY['Strepsils']),
('halls', 'Halls Mentho-Lyptus', 'Mentol + eucalipto', 'Caja x 12 caramelos', 'Descongestionante', 'Dolor de garganta', ARRAY['Halls']),
('pepto-bismol', 'Pepto-Bismol', 'Subsalicilato de bismuto', 'Frasco 120 ml', 'Antidiarreico', 'Diarrea y malestar estomacal', ARRAY['Pepto-Bismol','Pepto Bismol']),
('imodium', 'Imodium 2 mg', 'Loperamida', 'Caja x 12 cápsulas', 'Antidiarreico', 'Diarrea aguda', ARRAY['Imodium','Loperamida']),
('flagyl-500', 'Flagyl 500 mg', 'Metronidazol', 'Caja x 20 tabletas', 'Antibiótico', 'Infecciones bacterianas y parasitarias', ARRAY['Flagyl','Metronidazol']),
('amoxidal-duo', 'Amoxidal Duo 875 mg', 'Amoxicilina + ácido clavulánico', 'Caja x 14 tabletas', 'Antibiótico', 'Infecciones respiratorias', ARRAY['Amoxidal Duo','Augmentin','Curam']),
('augmentin-bid', 'Augmentin BID 875 mg', 'Amoxicilina + ácido clavulánico', 'Caja x 14 tabletas', 'Antibiótico', 'Infecciones bacterianas', ARRAY['Augmentin','Amoxidal','Curam']),
('clavulin', 'Clavulin 875 mg', 'Amoxicilina + ácido clavulánico', 'Caja x 14 tabletas', 'Antibiótico', 'Infecciones bacterianas', ARRAY['Clavulin','Augmentin','Curam']),
('zyrtec-d', 'Zyrtec-D', 'Cetirizina + pseudoefedrina', 'Caja x 14 tabletas', 'Antihistamínico', 'Alergia y congestión', ARRAY['Zyrtec-D','Reactine-D']),
('claritin-d', 'Claritin-D', 'Loratadina + pseudoefedrina', 'Caja x 14 tabletas', 'Antihistamínico', 'Alergia y congestión', ARRAY['Claritin-D','Clarityne-D']),
('actifed', 'Actifed', 'Triprolidina + pseudoefedrina', 'Jarabe 120 ml', 'Antigripal', 'Resfriado y alergia', ARRAY['Actifed']),
('tabcin', 'Tabcin Día y Noche', 'Acetaminofén + clorfeniramina + fenilefrina', 'Caja x 12 cápsulas', 'Antigripal', 'Síntomas de gripe', ARRAY['Tabcin']),
('panadol-multisintomas', 'Panadol Multisíntomas', 'Acetaminofén + cafeína + fenilefrina', 'Caja x 24 tabletas', 'Antigripal', 'Síntomas de gripe', ARRAY['Panadol Multisíntomas','Panadol Gripe']),
('redoxon', 'Redoxon Vitamina C 1g', 'Ácido ascórbico', 'Tubo x 10 tabletas efervescentes', 'Suplemento', 'Defensas e inmunidad', ARRAY['Redoxon','Vitamina C']),
('berocca', 'Berocca Performance', 'Vitaminas B + vitamina C + magnesio', 'Tubo x 15 tabletas efervescentes', 'Suplemento', 'Energía y concentración', ARRAY['Berocca']),
('centrum', 'Centrum Adultos', 'Multivitamínico', 'Frasco x 30 tabletas', 'Suplemento', 'Multivitamínico', ARRAY['Centrum']),
('viagra-50', 'Viagra 50 mg', 'Sildenafil', 'Caja x 4 tabletas', 'Disfunción eréctil', 'Disfunción eréctil', ARRAY['Viagra','Sildenafil','Magnus']),
('cialis-20', 'Cialis 20 mg', 'Tadalafil', 'Caja x 4 tabletas', 'Disfunción eréctil', 'Disfunción eréctil', ARRAY['Cialis','Tadalafil']),
('canesten-crema', 'Canesten Crema', 'Clotrimazol', 'Tubo 20 g', 'Antimicótico', 'Infecciones por hongos', ARRAY['Canesten','Clotrimazol']),
('ginoxin', 'Ginoxin Óvulos', 'Clotrimazol', 'Caja x 6 óvulos', 'Antimicótico', 'Infecciones vaginales', ARRAY['Ginoxin','Canesten']),
('plidan-compuesto', 'Plidan Compuesto', 'Hioscina + dipirona', 'Caja x 20 tabletas', 'Antiespasmódico', 'Cólicos y dolor', ARRAY['Plidan']),
('novalgina', 'Novalgina 500 mg', 'Dipirona (metamizol)', 'Caja x 20 tabletas', 'Analgésico', 'Dolor y fiebre fuerte', ARRAY['Novalgina','Conmel','Dipirona']),
('nexium-40', 'Nexium 40 mg', 'Esomeprazol', 'Caja x 14 cápsulas', 'Antiácido', 'Reflujo y úlcera', ARRAY['Nexium','Esomeprazol'])
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  active_ingredient = EXCLUDED.active_ingredient,
  presentation = EXCLUDED.presentation,
  category = EXCLUDED.category,
  indication = EXCLUDED.indication,
  brand_names = EXCLUDED.brand_names;
